### ISSUE TITLE
Compatibility with non-declarative namespaces

### ISSUE THREAD

**Issue by JordanMLee** [amandeepmittal/mobilenet-tfjs-expo#2]
After cloning the repo and running yarn install, I get error ` Namespace not marked type-only declare. Non-declarative namespaces are only supported experimentally in Babel.`  I tried enabling non-declarative namespaces by following https://babeljs.io/docs/en/babel-plugin-transform-typescript, however I run into issues when setting the allowNamespaces option in  `babel.config.js`. Any idea how to fix this. Here is my current babel.config.js 
`module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ["@babel/plugin-transform-typescript",{
      allowNamespaces: true
    }]
  };
};`

**Comment by amandeepmittal** [comment]
Hey @JordanMLee are you using TypeScript? If yes, please have a look at this: https://github.com/tensorflow/tfjs/issues/2400

**Comment by JordanMLee** [comment]
Thanks @amandeepmittal  🎉 The comment from ItachiUchiha91 in the link above solved this issue.  I'm not using expo managed typescript, however some of the files in @tensorflow/tfjs and @tensorflow/tfjs-react-native use typescript, which is where the error comes from. Everything in that comment was required to properly import these libraries.

**Comment by amandeepmittal** [comment]
I am glad it helped 😃
